version: '3.4'
services:
  zeo:
    image: iasmartweb/ideabox
    user: imio
    environment:
        - HOME=/home/imio
    volumes:
        - ./var/blobstorage:/home/imio/imio-website/var/blobstorage
        - ./var/filestorage:/home/imio/imio-website/var/filestorage
    working_dir: /home/imio/imio-website
    command: /home/imio/imio-website/bin/zeoserver fg
  instance:
    image: iasmartweb/ideabox
    user: imio
    ports:
      - "8081:8081"
    links:
      - zeo:db
    working_dir: /home/imio/imio-website
    volumes:
        - ./var/blobstorage:/home/imio/imio-website/var/blobstorage
    environment:
      - MEMCACHE_SERVER=127.0.0.1
      - MEMCACHE_DEFAULT_AGE=10800
      - ENV=dev
      - CACHING_SERVERS=http://frontend2.lan.imio.be:5000 http://frontend3.lan.imio.be:5000
      - DOMAINS=localhost
      - ZEO_HOST=db
      - ZEO_PORT=8100
    command: /home/imio/imio-website/bin/instance fg
