version: '3.4'
services:
  zeo:
    build:
      context: .
    image: imioideabox
    user: imio
    volumes:
      - ./var/blobstorage:/home/imio/plone/var/blobstorage
      - ./var/filestorage:/home/imio/plone/var/filestorage
    command: /home/imio/plone/bin/zeoserver fg
  instance:
    image: imioideabox
    user: imio
    links:
      - zeo:db
    depends_on:
      - reverseproxy
    command: /home/imio/plone/bin/instance fg
    labels:
      - "traefik.frontend.rule=Host:localhost; AddPrefix: /VirtualHostBase/http/localhost/plone/VirtualHostRoot"

  reverseproxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
